version: 2.1

orbs:
  gcloud: circleci/gcp-cli@1.0.0
  gcr: circleci/gcp-gcr@0.0.2
  k8s: circleci/kubernetes@0.1.0

jobs:

  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

  gcr-push:
    jobs:
      - gcr/build_and_push_image:
          context: kubone
          image: bots/pybot
          tag: v${CIRCLE_BUILD_NUM}
          filters:
            branches:
              only:
                - master